In [1]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import os

In [2]:
df = pd.read_excel(os.path.join( "Resources", "all_alpha_18.xlsx"))
df.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Stnd,Stnd Description,Underhood ID,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay,Comb CO2
0,ACURA ILX,2.4,4.0,AMS-8,2WD,Gasoline,CA,L3ULEV125,California LEV-III ULEV125,JHNXV02.4NH3,small car,3,25,35,29,6,No,309
1,ACURA ILX,2.4,4.0,AMS-8,2WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,JHNXV02.4NH3,small car,3,25,35,29,6,No,309
2,ACURA MDX,3.0,6.0,AMS-7,4WD,Gasoline,CA,L3ULEV125,California LEV-III ULEV125,JHNXV03.08H3,small SUV,3,26,27,27,6,No,330
3,ACURA MDX,3.0,6.0,AMS-7,4WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,JHNXV03.08H3,small SUV,3,26,27,27,6,No,330
4,ACURA MDX,3.5,6.0,SemiAuto-9,2WD,Gasoline,CA,L3ULEV125,California LEV-III ULEV125,JHNXV03.5RH3,small SUV,3,19,27,22,4,No,404

In [7]:
df2 = pd.read_csv(os.path.join( "Resources", "unique-models.csv"))
df2.head()
df1 = df2.rename({'MODEL': 'Model'}, axis='index')
df1

                          MODEL
0                 Toyota Tundra
1                 Toyota Tacoma
2                Toyota 4Runner
3   Smart Fortwo Electric Drive
4                   Nissan Leaf
5                 Jeep Wrangler
6                     Jaguar XJ
7               Honda Ridgeline
8                    GMC Sierra
9                    GMC Canyon
10          Chevrolet Silverado
11           Chevrolet Colorado
12                 BMW 7-series
13                     Fiat 500

In [ ]:
mergedStuff = pd.merge(df, df2, on=['Model'], how='inner')
mergedStuff.head()